name: iOS Build
run-name: iOS Build ${{ inputs.build_id || github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      build_id:
        description: "Unique build identifier"
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Expo Prebuild
        run: npx expo prebuild --platform ios --clean

      - name: Export JS Bundle
        run: npm run bundle:ios

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS IPA Unsigned
        run: |
          cd ios
          SCHEME=$(xcodebuild -workspace *.xcworkspace -list -json | node -e "const fs = require('fs'); const data = JSON.parse(fs.readFileSync(0, 'utf-8')); console.log((data.workspace || data.project).schemes[0]);")
          xcodebuild -workspace *.xcworkspace -scheme "$SCHEME" -configuration Release -sdk iphoneos -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO AD_HOC_CODE_SIGNING_ALLOWED=YES build
          mkdir -p ../Payload
          cp -r build/Build/Products/Release-iphoneos/*.app ../Payload/
          cd ..
          zip -r Gym.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Gym-${{ inputs.build_id }}-Release
          path: Gym.ipa
